name: auto alpha publish to npm
on:
  push:
    branches:
      - main
    paths:
      - "**.js"
      - "**.ts"
      - "**.tsx"
      - "**.json"
      - "!**.stories.tsx"
      - "!**.test.ts"
      - "!**.md"
      - "!**.mdx"
  pull_request:
    paths:
      - ".github/workflows/auto-alpha-publish-to-npm.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          key: node-${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          path: |
            node_modules
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true
      - name: Build package
        run: yarn build
      - name: Update version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npm version prepatch --preid alpha-$(git rev-parse --short HEAD)
      - name: Publish
        run: npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
