name: deploy preview

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
      id-token: write
      actions: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Create a website
        run: mkdir -p build && echo -e "<pre>$(date -u)\n$GITHUB_SHA\n$GITHUB_REF</pre>" > build/index.html

      - name: Deploy to netlify
        id: deploy-to-netlify
        run: echo "::set-output name=NETLIFY_LOG_JSON::$(npx netlify-cli deploy --dir=./build --message="${{ github.event.pull_request.title }}" --alias=deploy-preview-${{ github.event.number }} --json | tr -d '\n')"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - run: echo ${{ steps.deploy-to-netlify.outputs.NETLIFY_LOG_JSON }}

      - name: Find Comment
        if: success() && github.event.number
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: "github-actions[bot]"
          body-includes: "<!-- NETLIFY_DEPLOY_LOG -->"

      - name: Create comment
        if: success() && github.event.number && steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            <!-- NETLIFY_DEPLOY_LOG -->
            ### <span aria-hidden="true">✅</span> Deploy Preview ready!
            |  Name | Link |
            |---------------------------------|------------------------|
            |<span aria-hidden="true">🔨</span> Latest commit | ${{ github.sha }} |
            |<span aria-hidden="true">🔍</span> Latest deploy log | ${{ fromJson(steps.deploy-to-netlify.outputs.NETLIFY_LOG_JSON).logs }} |
            |<span aria-hidden="true">😎</span> Deploy Preview | ${{ fromJson(steps.deploy-to-netlify.outputs.NETLIFY_LOG_JSON).deploy_url }} <br> https://${{ fromJson(steps.deploy-to-netlify.outputs.NETLIFY_LOG_JSON).deploy_id }}--${{ fromJson(steps.deploy-to-netlify.outputs.NETLIFY_LOG_JSON).site_name }}.netlify.app|

      - name: Update comment
        if: success() && github.event.number && steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            <!-- NETLIFY_DEPLOY_LOG -->
            ### <span aria-hidden="true">✅</span> Deploy Preview ready!
            |  Name | Link |
            |---------------------------------|------------------------|
            |<span aria-hidden="true">🔨</span> Latest commit | ${{ github.sha }} |
            |<span aria-hidden="true">🔍</span> Latest deploy log | ${{ fromJson(steps.deploy-to-netlify.outputs.NETLIFY_LOG_JSON).logs }} |
            |<span aria-hidden="true">😎</span> Deploy Preview | ${{ fromJson(steps.deploy-to-netlify.outputs.NETLIFY_LOG_JSON).deploy_url }} <br> https://${{ fromJson(steps.deploy-to-netlify.outputs.NETLIFY_LOG_JSON).deploy_id }}--${{ fromJson(steps.deploy-to-netlify.outputs.NETLIFY_LOG_JSON).site_name }}.netlify.app|
